/** Maps dashboard routes to required page permissions */
export const ROUTE_PERMISSIONS: Record<string, string | null> = {
  "/dashboard": null,
  "/dashboard/audit": "Permissions.Manage",
  "/dashboard/permissions": "Permissions.Manage",
  "/dashboard/admin/permissions": "Permissions.Manage",
  "/dashboard/admin/roles": "Permissions.Manage",
  "/dashboard/admin/user-roles": "Permissions.Manage",
  "/dashboard/admin/user-permissions": "Permissions.Manage",
  "/dashboard/admin/users": "Users.View",
  "/dashboard/admin/users/create": "Users.Create",
  "/dashboard/customers": "Customer.View",
  "/dashboard/units": "Unit.View",
  "/dashboard/item-formats": "ItemFormat.View",
  "/dashboard/item-origins": "ItemOrigin.View",
  "/dashboard/companies": "Company.View",
  "/dashboard/pharm": "Pharm.View",
  "/dashboard/accounts-chart": null,
  "/dashboard/collection-voucher": null,
  "/dashboard/payment-voucher": null,
  "/dashboard/pending-vouchers": null,
  "/dashboard/manual-journal": null,
  "/dashboard/journal": null,
  "/dashboard/ledger": null,
  "/dashboard/cost-centers": null,
  "/dashboard/stores": null,
  "/dashboard/vendors": null,
  "/dashboard/sales-pay-method": "SalesPayMethod.View",
  "/dashboard/sales-service": "SalesService.View",
  "/dashboard/sales-service-assignment": "SalesServiceAssignment.View",
  "/dashboard/sales-payment-assiment": "SalesPaymentAssiment.View",
  "/dashboard/stock": "Stock.View",
  "/dashboard/inventory": "Stock.View",
  "/dashboard/batch-management": "Stock.View",
  "/dashboard/batch-traceability": "BatchTraceability.View",
  "/dashboard/transactions/inventory-adjustment": "Stock.View",
  "/dashboard/transactions/inventory-adjustment/posting": "Stock.View",
  "/dashboard/item-catalog": "ItemCatalog.View",
  "/dashboard/groups": "Group.View",
  "/dashboard/brands": "Brand.View",
  "/dashboard/employ-info": null,
  "/dashboard/transactions/purchase": null,
  "/dashboard/pharm/transactions/pharmacy-purchase": "Sales.View",
  "/dashboard/pharm/transactions/pharmacy-acceptance": "Sales.View",
  "/dashboard/pharm/transactions/stor-to-pharm": "Sales.View",
  "/dashboard/pharm/transactions/pharmacy-transfer": "Sales.View",
  "/dashboard/transactions/purchase/reversal": null,
  "/dashboard/transactions/purchase/invoice-draft": null,
  "/dashboard/transactions/return": null,
  "/dashboard/item-transactions": null,
  "/dashboard/movement-setting": null,
  "/dashboard/sales-movement-setting": null,
  "/dashboard/sales": "Sales.View",
  "/dashboard/shift": "Sales.View",
};

export const PERMISSIONS = {
  customer: {
    view: "Customer.View",
    create: "Customer.Create",
    edit: "Customer.Edit",
    delete: "Customer.Delete",
    export: "Customer.Export",
    page: "CustomerPage",
    saveButton: "CustomerPage.SaveButton",
    deleteButton: "CustomerPage.DeleteButton",
  },
  itemFormat: {
    view: "ItemFormat.View",
    create: "ItemFormat.Create",
    edit: "ItemFormat.Edit",
    delete: "ItemFormat.Delete",
  },
  unit: {
    view: "Unit.View",
    create: "Unit.Create",
    edit: "Unit.Edit",
    delete: "Unit.Delete",
  },
  itemOrigin: {
    view: "ItemOrigin.View",
    create: "ItemOrigin.Create",
    edit: "ItemOrigin.Edit",
    delete: "ItemOrigin.Delete",
  },
  company: {
    view: "Company.View",
    create: "Company.Create",
    edit: "Company.Edit",
    delete: "Company.Delete",
    import: "Company.Import",
    export: "Company.Export",
  },
  pharm: {
    view: "Pharm.View",
    create: "Pharm.Create",
    edit: "Pharm.Edit",
    delete: "Pharm.Delete",
  },
  stock: {
    view: "Stock.View",
  },
  batchTraceability: {
    view: "BatchTraceability.View",
  },
  itemCatalog: {
    view: "ItemCatalog.View",
    create: "ItemCatalog.Create",
    edit: "ItemCatalog.Edit",
    delete: "ItemCatalog.Delete",
    import: "ItemCatalog.Import",
    export: "ItemCatalog.Export",
  },
  group: {
    view: "Group.View",
    create: "Group.Create",
    edit: "Group.Edit",
    delete: "Group.Delete",
  },
  brand: {
    view: "Brand.View",
    create: "Brand.Create",
    edit: "Brand.Edit",
    delete: "Brand.Delete",
  },
  salesPayMethod: {
    view: "SalesPayMethod.View",
    create: "SalesPayMethod.Create",
    edit: "SalesPayMethod.Edit",
    delete: "SalesPayMethod.Delete",
  },
  salesService: {
    view: "SalesService.View",
    create: "SalesService.Create",
    edit: "SalesService.Edit",
    delete: "SalesService.Delete",
  },
  salesServiceAssignment: {
    view: "SalesServiceAssignment.View",
    create: "SalesServiceAssignment.Create",
    edit: "SalesServiceAssignment.Edit",
    delete: "SalesServiceAssignment.Delete",
  },
  salesPaymentAssiment: {
    view: "SalesPaymentAssiment.View",
    create: "SalesPaymentAssiment.Create",
    edit: "SalesPaymentAssiment.Edit",
    delete: "SalesPaymentAssiment.Delete",
  },
  employInfo: {
    view: "EmployInfo.View",
    create: "EmployInfo.Create",
    edit: "EmployInfo.Edit",
    delete: "EmployInfo.Delete",
  },
  purchase: {
    /** Set when PurTransH RBAC is seeded on Alfa API */
    view: null as string | null,
  },
  movParient: {
    /** Set when MovParient RBAC is seeded on Alfa API */
    view: null as string | null,
    create: null as string | null,
    edit: null as string | null,
    delete: null as string | null,
  },
  movment: {
    view: null as string | null,
    create: null as string | null,
    edit: null as string | null,
    delete: null as string | null,
  },
  salesMovment: {
    view: null as string | null,
    edit: null as string | null,
  },
  permissions: {
    manage: "Permissions.Manage",
  },
  pharmacyScope: {
    manage: "PharmacyScope.Manage",
  },
  sales: {
    view: "Sales.View",
  },
  users: {
    view: "Users.View",
    create: "Users.Create",
    edit: "Users.Edit",
    delete: "Users.Delete",
  },
} as const;

export const NAV_LINKS = [
  { href: "/dashboard", label: "Overview", permission: null },
  {
    href: "/dashboard/audit",
    label: "System Audit Center",
    permission: PERMISSIONS.permissions.manage,
  },
  {
    href: "/dashboard/admin/permissions",
    label: "Create Permissions",
    permission: PERMISSIONS.permissions.manage,
  },
  {
    href: "/dashboard/admin/roles",
    label: "Create Roles",
    permission: PERMISSIONS.permissions.manage,
  },
  {
    href: "/dashboard/admin/users",
    label: "Users",
    permission: PERMISSIONS.users.view,
  },
  {
    href: "/dashboard/admin/user-roles",
    label: "Assign User Roles",
    permission: PERMISSIONS.permissions.manage,
  },
  {
    href: "/dashboard/permissions",
    label: "Role Permissions",
    permission: PERMISSIONS.permissions.manage,
  },
  {
    href: "/dashboard/vendors",
    label: "Vendors",
    permission: null,
  },
  {
    href: "/dashboard/sales-pay-method",
    label: "Sales Payment Method",
    permission: PERMISSIONS.salesPayMethod.view,
  },
  {
    href: "/dashboard/sales-service",
    label: "Sales Service",
    permission: PERMISSIONS.salesService.view,
  },
  {
    href: "/dashboard/sales-service-assignment",
    label: "Sales Service Assignment",
    permission: PERMISSIONS.salesServiceAssignment.view,
  },
  {
    href: "/dashboard/sales-payment-assiment",
    label: "Sales Payment Assignment",
    permission: PERMISSIONS.salesPaymentAssiment.view,
  },
  {
    href: "/dashboard/customers",
    label: "Customers",
    permission: PERMISSIONS.customer.view,
  },
  {
    href: "/dashboard/units",
    label: "Units",
    permission: PERMISSIONS.unit.view,
  },
  {
    href: "/dashboard/item-formats",
    label: "Dosage Form",
    permission: PERMISSIONS.itemFormat.view,
  },
  {
    href: "/dashboard/item-origins",
    label: "Item Origins",
    permission: PERMISSIONS.itemOrigin.view,
  },
  {
    href: "/dashboard/companies",
    label: "Company",
    permission: PERMISSIONS.company.view,
  },
  {
    href: "/dashboard/pharm",
    label: "Pharm",
    permission: PERMISSIONS.pharm.view,
  },
  {
    href: "/dashboard/item-catalog",
    label: "Item Catalog",
    permission: PERMISSIONS.itemCatalog.view,
  },
  {
    href: "/dashboard/groups",
    label: "Groups",
    permission: PERMISSIONS.group.view,
  },
  {
    href: "/dashboard/brands",
    label: "Brands",
    permission: PERMISSIONS.brand.view,
  },
  {
    href: "/dashboard/item-transactions",
    label: "Move Parient",
    permission: PERMISSIONS.movParient.view,
  },
  {
    href: "/dashboard/movement-setting",
    label: "Movement Setting",
    permission: PERMISSIONS.movment.view,
  },
  {
    href: "/dashboard/sales-movement-setting",
    label: "Sales Movement Setting",
    permission: PERMISSIONS.salesMovment.view,
  },
] as const;

export const PERMISSION_TYPES = ["Page", "Control", "Action"] as const;
