export type PharmReciveExcelPreviewRow = {
  excelRowNumber: number;
  itmId: string;
  itmNameAr: string;
  itmNameEn: string;
  qnty: string;
  expDate?: string;
  batchNo?: string;
  salesPrice?: number;
  purshPrice?: number;
  costPrice?: number;
  unitId?: number | null;
};

export type PharmReciveExcelFieldError = {
  field: string;
  columnTitle: string;
  message: string;
};

export type PharmReciveExcelPreviewRowValidated = PharmReciveExcelPreviewRow & {
  isValid: boolean;
  errors: PharmReciveExcelFieldError[];
  /** Original Excel row when this row was generated by allocation. */
  sourceExcelRowNumber?: number;
  isAllocatedRow?: boolean;
};

export type PharmReciveExcelProcessSummaryEntry = {
  code: string;
  excelQuantity: number;
  result: string;
  success: boolean;
  itmNameAr?: string;
  itmNameEn?: string;
  /** Original Excel row number when this entry came from a specific import row. */
  sourceExcelRowNumber?: number;
};

export type PharmReciveExcelPreview = {
  fileName: string;
  sheetName: string;
  rowCount: number;
  rows: PharmReciveExcelPreviewRow[];
};

export type PharmReciveExcelPreviewValidated = Omit<
  PharmReciveExcelPreview,
  "rows"
> & {
  rows: PharmReciveExcelPreviewRowValidated[];
  isValid: boolean;
  processComplete?: boolean;
};

export const PHARM_RECIVE_EXCEL_VALIDATION_SUMMARY =
  "The Excel file contains invalid data. Correct the highlighted rows and import again.";

export const PHARM_RECIVE_EXCEL_TEMPLATE_HEADERS = [
  "Code",
  "Arabic Name",
  "English Name",
  "Quantity",
] as const;
